export const RECEIVE = 'dashboard/RECEIVE'
export const UPDATE = 'dashboard/UPDATE'
export const RESET = 'dashboard/RESET'
export const LOADING = 'dashboard/LOADING'
export const ERROR = 'dashboard/ERROR'
export const CLEAR_ERROR = 'dashboard/CLEAR_ERROR'
