const colors = {
  black: '#000000',
  nightRider: '#2b2b2b',
  veryLightGray: '#cccccc',
  lightGray: '#f4f4f4',
  whiteGray: '#fafafa',
  lighterGray: '#f6f6f6',
  lineGray: '#f2f2f2',
  warmGray: '#9b9b9b',
  nobel: '#8b8b8b',
  mercury: '#e7e7e7',
  white: '#ffffff',
  yellow: '#fff2de',
  darkYellow: '#FB8700',
  green: '#19c657',
  darkGreen: '#00923F',
  darkPastelGreen: '#1db954',
  money: '#7abc30',
  brightBlue: '#368df7',
  cinnabar: '#f03636',
  supernova: '#fcad2d',
  orange: '#fb8f00',
  lightPink: '#ff4086',
  red: '#ff2929',
  darkRed: '#C02220',
  veryLightRed: '#fff2f2',
  veryLightBlue: '#e4ecf7',
  veryLightYellow: '#fff9f2',
  navyBlue: '#390077',
  marineBlue: '#272976',
  lightlessBlue: '#e4ecf7',
  solitude: '#e3e4e6',
  veryLightGreen: '#e0ffeb',
  redPrimary: '#ff0048',
  lightGray90: 'rgba(222, 224, 227, 0.9)',
  darkestGray: '#6d6d6d',
  darkTextGray: '#4a4a4a',
  black60: 'rgba(0, 0, 0, 0.6)',
  black10: 'rgba(0, 0, 0, 0.1)',
  black30: 'rgba(0, 0, 0, 0.27)',
  rgbaWhiteOpacity: opacity => `rgba(255,255,255,${opacity})`,
  blueLight: '#e4ecf7',
  stage: 'rgba(43, 43, 43, 0.8)',
  lightGreen: '#3edd8d',
  lightRed: '#f96666',
  blueLightSafe: '#d9eaff',
  shadowGray: '#d9dadb',
  disabledGray: '#6b6b6b',
  darkBlue: '#222470',
  walletMenu: '#9293BA',
  investedCardValue: '#f44910',
  loansTitle: '#cacbcc',
  dashed: '#efefef',
  reloadIcon: '#4B4D8B'
}

const gradients = {
  darkToLightGreen: [ colors.darkPastelGreen, colors.lightGreen ],
  lightToDarkBlue: [ '#3539c8', '#3032a1' ],
  lightToDarkYellow: [ '#fad961', '#f76b1c' ]
}

export default {
  ...colors,
  ...gradients,
  primary: colors.lightPink,
  secondary: colors.brightBlue,
  mutualBlue: colors.marineBlue,
  mutualPink: colors.lightPink,
  text: colors.nightRider,
  placeholder: colors.nobel,
  underline: colors.nobel,
  invalid: colors.red,
  disabled: colors.veryLightGray,
  separator: colors.solitude,
  border: colors.veryLightGray,
  overlay: colors.nightRider,
  background: colors.white,
  focused: colors.brightBlue,
  error: colors.red,
  menuAvatar: colors.darkBlue,
  pending: colors.supernova,
  scoreA: colors.darkGreen,
  scoreB: '#7ABC30',
  scoreC: '#FFCD00',
  scoreD: colors.darkYellow,
  scoreE: '#F44910',
  scoreF: colors.darkRed
}
